## Problem Set 01 Introducción a Python

## EJECUTA ESTA CELDA PARA AUTENTICARTE CON TU CUENTA DE GMAIL

In [ ]:
from mooclib import *
import inspect, urllib
html, auth_code, userinfo = google_authenticate(PORT_NUMBER=8080)
html

## <font style="color: red"> Esta práctica contiene 4 ejercicios <!-- ONLY IN NOTEBOOK -->

### Ejercicio 1: Generación de una matriz

Completa la función `single_value_matrix` para que devuelva una matriz de tamaño $n\_rows \times n\_cols$ con todos los elementos igual a $value$. Ejecuta y depura tu código con entradas de prueba, verifica que la salida es la esperada y prueba con nuevos valores.

#### Ejemplo de ejecución

    > single_value_matrix(n_rows=3, n_cols=4, value=5)
    
      [[ 5.  5.  5.  5.]
       [ 5.  5.  5.  5.]
       [ 5.  5.  5.  5.]]
     
_Sugerencia_: Usa la función `np.ones` de Numpy [[ref](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)]

In [ ]:
import numpy as np

def single_value_matrix(n_rows, n_cols, value):
    ## --- TU CODIGO AQUI ---
    result = ???
    return result

import urllib, inspect
src1 = urllib.quote_plus(inspect.getsource(single_value_matrix))

In [ ]:
# -- VERIFICA TU CODIGO --
print single_value_matrix(n_rows=3, n_cols=4, value=5)
print single_value_matrix(n_rows=4, n_cols=2, value=3.45)

#### evaluate your answer before submitting:

In [ ]:
!./run CHECK_SOLUTION PS1_1 $src1

#### submit your answer (you must be connected to internet)

In [ ]:
!./run SUBMIT_SOLUTION PS1_1 $src1

### Ejercicio 2: Suma de diferencias cuadradas de matrices

Dadas dos matrices de igual tamaño, $A \in \mathbb{R}^{m\times n}$ y $B \in \mathbb{R}^{m\times n}$ la suma de las diferencias cuadradas entre los elementos de la matriz se define por:


$$sum\_squared\_difference(A,B) = \sum_{i=0}^m \sum_{j=0}^n (a_{ij} - b_{ij})^2$$


donde $a_{ij}$ es el elemento de la fila $i$ y columna $j$ de la matriz $A$. Completa la función `sum_squared_difference` con esta definición.


#### Ejemplo de ejecución

    > A = np.array([[1,2],[3,4]])
    > B = np.array([[0,3],[4,6]])
    > sum_squared_difference(A,B)
    
      7
      
_Sugerencia_ Usa la función `np.sum` de Numpy [[ref](http://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html)]

In [ ]:
import numpy as np

def sum_squared_difference(A,B):
    ## --- TU CODIGO AQUI ---
    result = ???
    return result

import urllib, inspect
src2 = urllib.quote_plus(inspect.getsource(sum_squared_difference))

In [ ]:
# VERIFICA TU CODIGO
A = np.array([[1,2],[3,4]])
B = np.array([[0,3],[4,6]])
print sum_squared_difference(A,B)

#### evaluate your answer before submitting:

In [ ]:
!./run CHECK_SOLUTION PS1_2 $src2

In [ ]:
!./run SUBMIT_SOLUTION PS1_2 $src2

### Ejercicio 3: Selección de elementos

La función `seleccion_mayor` toma dos argumentos: un vector y un escalar. Debe de devolver los elementos del vector que son estrictamente mayores que el escalar 

#### Ejemplo de ejecución

    > v1 = np.array([-4,5,-1,2,3,10,-2])
    > print seleccion_mayor(v1, 0)
    > print seleccion_mayor(v1,-2)
    > print seleccion_mayor(v1,12)    
    
    [ 5  2  3 10]
    [ 5 -1  2  3 10]
    []        

In [ ]:
import numpy as np

def seleccion_mayor (V, umbral):
    # TU CODIGO AQUI ----
    result = ???
    return result

import urllib, inspect
src3 = urllib.quote_plus(inspect.getsource(seleccion_mayor))

In [ ]:
v1 = np.array([-4,5,-1,2,3,10,-2])
print seleccion_mayor(v1, 0)
print seleccion_mayor(v1,-2)
print seleccion_mayor(v1,12)

#### evaluate your answer before submitting:

In [ ]:
!./run CHECK_SOLUTION PS1_3 $src3

#### submit your answer (you must be connected to internet)

In [ ]:
!./run SUBMIT_SOLUTION PS1_3 $src3

### Ejercicio 4: Promedios y desviaciones estándar

La función `means_stds` debe de retornar:

- una tupla con la lista de promedios y la lista de desviaciones estándar por columna si `eje` es `"columnas"`
- una tupla con la lista de promedios y la lista de desviaciones estándar por fila si `eje` es `"filas"`
- la tupla `[None, None]` si la dimensión de de `m` no es 2.
- la tupla `[None, None]` si `eje` no es ninguno de los dos valores anteriores

El valor por defecto de `eje` debe de ser `"columnas"`

**Ejemplo de ejecución**
    > A = np.array([[1,2,3],[3,4,5]])
    > means_stds(A)
    
    (array([ 2.,  3.,  4.]), array([ 1.,  1.,  1.]))
    
    > means_stds(A, eje="filas")
    (array([ 2.,  4.]), array([ 0.81649658,  0.81649658]))

    > V = np.array([1,2,3])
    > means_stds(V)
    
    [None, None]

    > M = np.random.random((2,2,2))
    > means_stds(M)
    
    [None, None]

<small><small>
el operador de comparación es `==`, por ejemplo:

    if a==1:
       print "a es 1"

</small></small>

In [ ]:
import numpy as np

def means_stds(A, eje="columnas"):
    # TU CODIGO AQUI ----
    result = ????
    return result

import urllib, inspect
src4 = urllib.quote_plus(inspect.getsource(means_stds))

In [ ]:
## VERIFICA TU CODIGO
A = np.array([[1,2,3],[3,4,5]])
print means_stds(A)
print means_stds(A, eje="columnas")
print means_stds(A, eje="filas")

V = np.array([1,2,3])
print means_stds(V)

#### evaluate your answer before submitting:

In [ ]:
!./run CHECK_SOLUTION PS1_4 $src4

#### submit your answer (you must be connected to internet)

In [ ]:
!./run SUBMIT_SOLUTION PS1_4 $src4